### PR TITLE
Bugfix for running on linux without bundled JRE

### PR DESCRIPTION
**Pull request by FibreFoX**
`app.runtime` will be changed in the case `JRE_HOME` is not set, using `JAVA_HOME` for its value instead

This is only the first part, looking for "known locations" is not yet implemented, but this is ready to get merged, as this makes it possible to run the application when OracleJDK is installed.

### CODE REVIEW

**Comment by FibreFoX** [comment]
This is ment to fix #6

**Comment by AdamCarroll** [comment]
First of all, huge thanks for putting this together!

It looks like it's almost there but doesn't quite work for me.  I cloned your repo and built on Linux and see the following, installing with `JAVA_HOME` set but not `JRE_HOME`:
~~~
$ sudo dpkg -i package/build/jfx/native/vocabhunter-1.0.18-SNAPSHOT.deb
Selecting previously unselected package vocabhunter.
(Reading database ... 308353 files and directories currently installed.)
Preparing to unpack .../vocabhunter-1.0.18-SNAPSHOT.deb ...
Unpacking vocabhunter (1.0.18-SNAPSHOT) ...
Setting up vocabhunter (1.0.18-SNAPSHOT) ...
Adding shortcut to the menu
JRE_HOME is not set, checking for JAVA_HOME being set
Please make sure to set JRE_HOME variable before running VocabHunter
~~~

However this doesn't then fix the problem running from the desktop as the `app.home` doesn't get filled in:
~~~
$ grep 'app.runtime' /opt/VocabHunter/app/VocabHunter.cfg
app.runtime=
~~~

This means that starting from the desktop fails.  As the message in the in the install suggests, the program can be run from the command line by first setting `JRE_HOME`.  So I think the script may need a bit of tweeking before merging.

Thanks again for your efforts with this!

**Comment by FibreFoX** [comment]
As mentioned, this is only the first part 😄 you need to have `oracle-java8-set-default` being installed too, because this makes `JAVA_HOME` persistant as some script (namely `/etc/profiles.d/jdk.sh`). The part about having the location detected from the "known location" is still missing, therefor I've added that `Please make sure to set JRE_HOME variable before running VocabHunter`-message.

Do you prefer to merge this first half, or do you want to wait for the second half for merging?

**Comment by FibreFoX** [comment]
Hi @AdamCarroll , can you re-check this PR?

**Comment by AdamCarroll** [comment]
Hey this looks like it's making good progress!

I've just tried it out on an Unbuntu VM (again, without `oracle-java8-set-default`):
~~~
$ sudo dpkg -i package/build/jfx/native/vocabhunter-1.0.18-SNAPSHOT.deb
Selecting previously unselected package vocabhunter.
(Reading database ... 308353 files and directories currently installed.)
Preparing to unpack .../vocabhunter-1.0.18-SNAPSHOT.deb ...
Unpacking vocabhunter (1.0.18-SNAPSHOT) ...
Setting up vocabhunter (1.0.18-SNAPSHOT) ...
Adding shortcut to the menu
JRE_HOME is not set, checking for JAVA_HOME being set
JAVA_HOME is not set, checking for known locations
Please make sure to have Java installed and JRE_HOME variable set before running VocabHunter
~~~

However, it then exhibits the same problem as before:
~~~
$ cat /opt/VocabHunter/app/VocabHunter.cfg | grep 'app.runtime'
app.runtime=
~~~

Looking at your script, Java can indeed be found in one of your known locations:
~~~
$ ls /usr/lib/jvm/java-8-oracle/bin/java
/usr/lib/jvm/java-8-oracle/bin/java
~~~

So I think it's almost there but not quite.

Thanks for your efforts with this!

**Comment by FibreFoX** [comment]
@AdamCarroll oh snap ;) didn't checked it ... only typed it out of my head :D next update to this PR will contain something working (sorry)

**Comment by FibreFoX** [comment]
Hi @AdamCarroll, please check my last commit ;) I made a stupid mistake, now it finally produces some working result !

**Comment by FibreFoX** [comment]
In the case the user installed some other JDK or just has set JRE_HOME, this now will be handled when user calls `dpkg-reconfigure` by setting runtime to some empty value (like it is before).

**Comment by AdamCarroll** [comment]
@FibreFoX I've just merged your change.  Thanks for your help in fixing this problem!  I appreciate it.  And keep up the good work on your great plugin!

**Pull request merged**
